name: Back Sync Master to Develop

on:
  push:
    branches:
      - master

jobs:
  back-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync Master to Develop
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: master
          TO_BRANCH: develop
          PULL_REQUEST_TITLE: "Auto Sync: master → develop"
          PULL_REQUEST_BODY: "This pull request was created automatically to back-sync master to develop."
          PULL_REQUEST_AUTO_MERGE_METHOD: merge
